name: my_music_app
description: A personal music player app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  just_audio: ^0.9.36
  cached_network_image: ^3.3.1

flutter:
  uses-material-design: true
  
